---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-gitlab-ssh-key
data:
  id_rsa: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCL8hZ2Yd0PwUp8lrtwoOQ4VF1eJgkb1eVdxkHW5WMIrAAAAJhegIb9XoCG
    /QAAAAtzc2gtZWQyNTUxOQAAACCL8hZ2Yd0PwUp8lrtwoOQ4VF1eJgkb1eVdxkHW5WMIrA
    AAAEBZm5ViCAzRWwggrdLMSxB8+tHBVGvg+p8piwKpjPbCX4vyFnZh3Q/BSnyWu3Cg5DhU
    XV4mCRvV5V3GQdblYwisAAAAEHRlamFkQGxzbnNvZnQuaW4BAgMEBQ==
    -----END OPENSSH PRIVATE KEY-----
  known_hosts: |
    |1|1PXA1FmP819nDDTlYdx4th2IAT0=|ejhmCbLCOLrYEF+gyXQMJnb4/WI= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKNVBejU2IXp/peHo26mz1j4hP66PAfy0/ts6msU1TwvsU2bEJlldb7Cm1iAkFX95xoD5ux3duH0PrlQM7ZE7DQ=
    |1|TxKtUW7bL4FtWQVF6ximtbghbAI=|iHKXlJAcEz7+fXZTFfnJrhyi+C0= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKNVBejU2IXp/peHo26mz1j4hP66PAfy0/ts6msU1TwvsU2bEJlldb7Cm1iAkFX95xoD5ux3duH0PrlQM7ZE7DQ=
#kubectl create configmap wordpress-gitlab-ssh-key --from-file=teja-gitlab-intellasphere  --from-file=known_hosts
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-extraconfig
data:
  wordpress-extraconfig: |
    /* w3 total cache */
    define( 'WP_CACHE', true );




    /* specifying digital ocean keys for s3-uploads */

    define( 'S3_UPLOADS_BUCKET', 'intella-landingpages');
    define( 'S3_UPLOADS_KEY', '87d4L3FWsXV7a5DqoG9a');
    define( 'S3_UPLOADS_SECRET', 'CNvsIAZxGaC8TmilUYyeZq11oTmMGb8evCBqTfOS');
    //define( 'S3_UPLOADS_BUCKET_URL', 'https://landingpages.nyc3.digitaloceanspaces.com');
    define( 'S3_UPLOADS_BUCKET_CDN_URL', 'https://cdn.intellapages.com');
    define( 'S3_UPLOADS_BUCKET_URL', 'https://minio2.intellasphere.com/minio/intellatest');
    define( 'S3_UPLOADS_REGION', 'us' );
## this configmap only for Extra Wordpress Configuration... if no need please do not create this configmap.
---
apiVersion: apps/v1

kind: Deployment

metadata:
  name: wordpress-nginx
  labels:
    app: wordpress-nginx

spec:
#  replicas: 3
  selector:
    matchLabels:
      app: wordpress-nginx

  template:
    metadata:
      labels:
        app: wordpress-nginx

    spec: 
      restartPolicy: Always

      imagePullSecrets:
      - name: teja-azure-container-registry

      containers:
      - name: wordpress-fpm-alpine
        image: intellasphere.azurecr.io/wordpress:test4

        imagePullPolicy: Always

        env:
        - name: WORDPRESS_DB_HOST
          value: "private-test-intellapages-do-user-1895504-0.b.db.ondigitalocean.com:25060"

        - name: WORDPRESS_DB_USER
          value: "intellapages"

        - name: WORDPRESS_DB_PASSWORD
          value: "In73LLaPA9e$"

        - name: WORDPRESS_DB_NAME
          value: "intellapages"

        - name: WORDPRESS_TABLE_PREFIX
          value: "wp_"

        - name: WORDPRESS_AUTH_KEY
          value: "-N#h4L)4L(|iXj3jJdZ^}H]-ubXOEVtk^kp-[|HzmU||d8Y/xtY&iAa:zNIxbiO%"

        - name: WORDPRESS_SECURE_AUTH_KEY
          value: ";O8wAE=L5~x>8we2jX5Q;cp1_DYXJVLm1*W^6V3I<)9-^`j`.~@fode&o4*jS>&+"

        - name: WORDPRESS_LOGGED_IN_KEY
          value: "zb4w=B1gQ}Oe+9ZZ]3|68x9M(#q$?Q9hK*s~HF&Tqb5Za)M;eW_6<+szGGr~ss)="

        - name: WORDPRESS_NONCE_KEY
          value: "luYh>&051THe3@8XrJ}H4z xV]U/0$l~V>4rMJ-$mTw%}|EA~f>nP;G5F:].~{{+"

        - name: WORDPRESS_AUTH_SALT
          value: "`.1}wH>aCj4<V_9X^!G,yI2-lX5+i&+KsP&=&[Iz{2]?%R,2cdXSxQ{~/mT|;yb6"

        - name: WORDPRESS_SECURE_AUTH_SALT
          value: "r;Jg(E7!=H3K+@(k@ttC[D_(, gpN28ScU<,Ry-zz~-~!AWAnU7UQ,&c4jOMf(XD"

        - name: WORDPRESS_LOGGED_IN_SALT
          value: "iff66Kj<N_(FfGL8+)JK3t5-4B*xabfyj)-yyUJO%a J:1)O#$X2%/0ubv=;.p-c"

        - name: WORDPRESS_NONCE_SALT
          value: "2kTd+SKr@_<RJi$>,Q.7 $bav_3|oc<6VE?PNl|ZeqC$[lQ<HE)r0by5`X,7P?]e"

        - name: WORDPRESS_DEBUG
          value:

        - name: WORDPRESS_CONFIG_EXTRA  ## use this environment variable only when ConfigMap --> "wordpress-extraconfig" is defined.
          valueFrom:
            configMapKeyRef:
              name: wordpress-extraconfig
              key: wordpress-extraconfig

        volumeMounts:
        - mountPath: /var/www/html
          name: shared-data-dir

        - name: trusted-keys
          mountPath: /root/.ssh/

        - mountPath: /root/composermount
          name: composerfile

        resources:
          requests:
            cpu: 300m
            memory: 200Mi
#          limits:
#            cpu: 1000m
#            memory: 2000Mi

        ports:
        - containerPort: 9000

#        startupProbe:
#          tcpSocket:
#            port: 9000
#          successThreshold: 1
#          failureThreshold: 30
#          periodSeconds: 10

#        livenessProbe:
#          tcpSocket:
#            port: 9000
#          initialDelaySeconds: 5
#          periodSeconds: 10

#        readinessProbe:
#          tcpSocket:
#            port: 9000
#          initialDelaySeconds: 5
#          periodSeconds: 10

      - name: nginx
        image: intellasphere.azurecr.io/nginx:test1

        imagePullPolicy: Always

        volumeMounts:
        - mountPath: /var/www/html
          name: shared-data-dir

        ports:
        - containerPort: 80
          name: http

#        - containerPort: 443
#          name: https

#        startupProbe:
#          httpGet:
#            path: /
#            port: http
#            httpHeaders:
#          successThreshold: 1
#          failureThreshold: 30
#          periodSeconds: 10

#        livenessProbe:
#          httpGet:
#            path: /
#            port: http
#            httpHeaders:
#          initialDelaySeconds: 3
#          periodSeconds: 3

#        readinessProbe:
#          httpGet:
#            path: /
#            port: http
#          initialDelaySeconds: 3
#          periodSeconds: 3

      volumes:
      - name: shared-data-dir
        emptyDir: {}

      - name: trusted-keys
        configMap:
          name: wordpress-gitlab-ssh-key
          defaultMode: 0600
          items:
          - key: id_rsa
            path: id_rsa
          - key: known_hosts
            path: known_hosts

      - name: composerfile
        configMap:
          name: wordpress-multisite-composerfile
          items:
          - key: composer.json
            path: composer.json