apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  
  persistentVolumeReclaimPolicy: Retain 
  nfs:
    path: /datadirtest
    server: 10.149.28.66
    #https://upendra-kumarage.medium.com/gcp-filestore-as-a-persistent-storage-in-google-kubernetes-engine-clusters-ab4f76b3411